### PR TITLE
Use prettier@1.8.0 to remove *Enable settings

### LINKED ISSUE #237: .prettierc overrides are ignored
It seems the plugin ignores prettier's overrides options. E.g. the following `.prettierc` fails for the directory `build_tools`:

```yaml
{
  "trailingComma": "all",
  "overrides": [
    {
      "files": "build_tools/*.js",
      "options": {
        "trailingComma": "es5"
      }
    }
  ]
}
```

It works fine if I run prettier from the command line.

### PR DESCRIPTION
**Pull request by azz**
This is obviously a breaking change but it greatly simplifies the process of supporting new languages (only bumping bundled prettier is required now).

Can't really see a reason to keep the `*Enable` settings any more...

We could do a 1.0.0 release with this and #252.

Fixes #237

### CODE REVIEW

**Comment by CiGit** [comment]
Initially I've seen `*Enable` as a way to disable prettier for a given language, to be able to use any other formatter. Or to add some *custom* languages which are supported by prettier (renamed language ids like `JSX` <-> `javascriptreact`)
It also allows some tricks like: https://github.com/prettier/prettier-vscode/issues/199#issuecomment-342382635

I'm really pleased if we can remove those `*Enable*`
I think we should do #199 before releasing next version with those changes.
v1 seems fine!

Sorry no time to review right now.

**Comment by CiGit** [comment]
travis seems to have some DNS issues with their mac box.

> Could not resolve host: github.com

> The maintenance work performed earlier today seems to have left some unresolved networking problems. No OSX builds are currently passing. We are investigating the situation.
Posted about 1 hour ago. Nov 09, 2017 - 13:06 UTC

File: src/utils.ts [hunk 1]
```diff
@@ -21,13 +21,22 @@ export function getConfig(uri?: Uri): PrettierVSCodeConfig {
 }
 
 export function allEnabledLanguages(): DocumentSelector {
-    const config = getConfig();
+    return (require('prettier') as Prettier)
+        .getSupportInfo()
+        .languages.reduce(
+            (ids, language) => [...ids, ...language.vscodeLanguageIds],
+            []
+        );
```
[the remark this answers is not in the document]
Comment (azz) [reply src/utils.ts]: Not quite, this is `flatMap`.
```js
> x = [{a:[1]}, {a:[2]}, {a:3}]
> x.reduce((ids, obj) => [...ids, ...obj.a], [])
[ 1, 2, 3 ]
> x.map(obj => obj.a)
[ [ 1 ], [ 2 ], [ 3 ] ]
```

[the remark this answers is not in the document]
Comment (CiGit) [reply src/utils.ts]: My bad, missed the spread part 😕

File: src/extension.ts [hunk 2]
```diff
@@ -1,21 +1,17 @@
...
     const editProvider = new EditProvider(fileIsIgnored);
     const languageSelector = allEnabledLanguages();
 
-    // CSS/json/graphql doesn't work with range yet.
-    const rangeLanguageSelector: DocumentSelector = [
-        ...config.javascriptEnable,
-        ...config.typescriptEnable,
-    ];
+    // Range selection is only supported for JS/TS
+    const rangeLanguageSelector = allJSLanguages();
```
[the remark this answers is not in the document]
Comment (azz) [reply src/extension.ts]: We should add range selection capability to `getSupportInfo`.

File: package.json [hunk 3]
```diff
@@ -243,9 +139,8 @@
   "dependencies": {
     "prettier-stylelint": "^0.4.1",
     "ignore": "^3.3.5",
-    "prettier": "1.7.3",
+    "prettier": "1.8.2",
```
[the remark this answers is not in the document]
Comment (azz) [reply package.json]: Looks like `requirePragma` is missing, too.

What about removing these options too, in favour of `.prettierrc`?

**Comment by azz** [comment]
> Is there any reason you prefer indexOf over includes ?

Nope, was just using it because I forgot this extension doesn't have to worry about node v4 compat.

**Comment by azz** [comment]
> Use case: I'd like to use prettier for JS but not for CSS. For CSS I'd like to use placeholder

How about a blacklist instead then?

```json
"prettier.disableLanguages": ["css"]
```

File: package.json (hunk 3 above)
[the remark this answers is not in the document]
Comment (CiGit) [reply package.json]: > What about removing these options too, in favour of .prettierrc?

Which options? All of them ?
I see them as useful when you have no project.
`requirePragma` seems to be useful only when in a project tho.

**Comment by CiGit** [comment]
> Can .prettierignore be used instead?

This would be really neat !!
Sadly I think this won't be possible with multi-root. We register one formatter but may have multiples prettierignore (1 per folder) 

The blacklist is the only (?) thing left I think

Maybe we should delay such implementation. See if someone asks for it.

File: CHANGELOG.md [hunk 4]
```diff
@@ -4,6 +4,9 @@ All notable changes to the "prettier-vscode" extension will be documented in thi
 Check [Keep a Changelog](http://keepachangelog.com/) for recommendations on how to structure this file.
 
 ## [Unreleased]
+- Removed all `*Enable` settings, these are now inferred from Prettier itself. Use scoped `editor.formatOnSave` to disable formatting some languages. (See README)
```
Comment (CiGit) [inline CHANGELOG.md]: I don't see formatOnSave as a synonym for disable.

File: src/PrettierEditProvider.ts [hunk 5]
```diff
@@ -79,27 +57,27 @@ async function format(
...
+    const dynamicParsers = getParsersFromLanguageId(languageId, localPrettier.version);
+    let useBundled = false;
+    let parser: ParserOption;
+
+    if (!dynamicParsers.length) {
+        const bundledParsers = getParsersFromLanguageId(
+            languageId,
+            bundledPrettier.version
+        );
+        parser = bundledParsers[0] || 'babylon';
```
Comment (CiGit) [inline src/PrettierEditProvider.ts]: In which case would it be the fallback?

**Comment by CiGit** [comment]
If you are happy with your PR, you can merge it 😉

File: src/PrettierEditProvider.ts (hunk 5 above)
Comment (azz) [reply src/PrettierEditProvider.ts]: Hopefully never!

**Comment by azz** [comment]
> Sadly I think this won't be possible with multi-root. We register one formatter but may have multiples prettierignore (1 per folder) and using prettierignore on format doesn't allow the user to register any other formatter. Well technically they can install an other formatter and only one of those would run. (never exactly understood which one)

https://code.visualstudio.com/docs/extensionAPI/vscode-api#languages.match
> Multiple providers can be registered for a language. In that case providers are sorted by their score and the best-matching provider is used. Failure of the selected provider will cause a failure of the whole operation.

Which sucks, because I think that means we can't support multi-root language disabling at all.

File: package.json (hunk 3 above)
[the remark this answers is not in the document]
Comment (lipis) [reply package.json]: Yes, let's not remove all of the options.. as already mentioned they are useful when there is no project :)

**Comment by lipis** [comment]
Are we there yet?!

(Don't mean to rush anything.. but it would be nice to start formatting markdown inside the editor 😄)

**Comment by azz** [comment]
Been super busy lately. Hopefully get back to this in the next few days.

**Comment by azz** [comment]
I think this is pretty much ready to go - we can look at ignore support in a focussed PR rather than adding it to this one.

File: src/PrettierEditProvider.ts [hunk 6]
```diff
@@ -48,6 +49,10 @@ async function format(
     ) as any;
     const localPrettier = requireLocalPkg(fileName, 'prettier') as Prettier;
 
+    if (vscodeConfig.disableLanguages.includes(languageId)) {
+        return text;
+    }
```
Comment (CiGit) [inline src/PrettierEditProvider.ts]: Instead of a noop we should just not register the formatter for those languages. To be able to use an other formatter for instance.

in extension.ts:
`languageSelector - disableLanguages`
`rangeLanguageSelector - disableLanguages`

This means "restart required" :smile:

File: src/PrettierEditProvider.ts [hunk 7]
```diff
@@ -92,7 +97,8 @@ async function format(
             parser: parser,
             semi: vscodeConfig.semi,
             useTabs: vscodeConfig.useTabs,
-        },
+            proseWrap: vscodeConfig.proseWrap,
+        } as PrettierConfig,
```
Comment (CiGit) [inline src/PrettierEditProvider.ts]: Was there a problem without the cast?

File: src/PrettierEditProvider.ts (hunk 6 above)
Comment (CiGit) [reply src/PrettierEditProvider.ts]: Ok, never mind, forgot multi-root......

**Comment by lipis** [comment]
Approved?!!

**Comment by lipis** [comment]
and now we wait.. and now on refresh mode: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by CiGit** [comment]
Will publish it a little later, I'd like to merge #252 first.

File: src/PrettierEditProvider.ts (hunk 6 above)
Comment (CiGit) [reply src/PrettierEditProvider.ts]: In fact, It could be a `resource: "window"` scope settings. Like our old `*Enabled` settings.

**Comment by azz** [comment]
Shouldn't this have been published as 1.0.0 rather than 0.26.0?

File: src/PrettierEditProvider.ts (hunk 7 above)
Comment (azz) [reply src/PrettierEditProvider.ts]: There was no type-checking on it before. Now it will be an error if incorrect properties are added

File: src/PrettierEditProvider.ts (hunk 6 above)
Comment (azz) [reply src/PrettierEditProvider.ts]: IMO `"resource": "window"` should not exist because it doesn't do anything in multi-root. Seems annoying that there's no way to skipping formatting on a per-resource level.

Maybe a feature request to `return null` from a formatter to skip it in VSCode?

**Comment by lipis** [comment]
Lost opportunity for the tweet :) https://twitter.com/PrettierCode/status/933269965830082560 people like new versions especially when they reach 1.0.0

File: src/PrettierEditProvider.ts (hunk 6 above)
Comment (azz) [reply src/PrettierEditProvider.ts]: https://github.com/Microsoft/vscode/issues/38945

**Comment by CiGit** [comment]
I'd like to put `requireConfig` with 1.0.0 #67 #229.
Some long standing feature requests.

File: src/PrettierEditProvider.ts (hunk 6 above)
Comment (CiGit) [reply src/PrettierEditProvider.ts]: On VSCode's side might be a good thing. :+1:

Comment (azz) [reply src/PrettierEditProvider.ts]: It actually seems to work if you throw an error... https://github.com/Microsoft/vscode/issues/38945#issuecomment-346319330

```ts
    if (vscodeConfig.disableLanguages.includes(languageId)) {
        throw new Error('Skip me!');
    }
```

Comment (CiGit) [reply src/PrettierEditProvider.ts]: Seems great!  just waiting for a confirmation on that *functionality*. 
API says:
>Returns: A set of text edits or a thenable that resolves to such. The lack of a result can be signaled by returning undefined, null, or an empty array.
